### ISSUE TITLE
Clarification : Parameter Estimation API

### ISSUE THREAD

**Issue by nsankar** [birdepy/birdepy_project#8]
@bpatch  Firstly, Thanks for developing this great package with excellent documentation.

I am learning the library and am trying to connect the dots and interpret the APIs. I have a few questions on the below statement referred in the docs. where I am trying to understand the key "lambda-2" and "mu-2" functions from the perspective of the models , parameters and the APIs ..
![image](https://user-images.githubusercontent.com/431890/137581531-c573ac2a-9aed-4c34-ba1c-e30d3ec377d8.png)

Suppose, I have a population data (discrete time) and I use BirDepy estimator API to estimate the parameters from the data for the "Ricker model" , 
1) Does the return values of the estimator compute the following parameters indicated in a table in the doc which is as below ?
![image](https://user-images.githubusercontent.com/431890/137581652-52caf99d-47db-4fe3-a4f6-581ebda532c1.png)

2) Is it correct in my understanding that using the above estimated parameters as shown below, we can then compute the outcomes of these following two functions ? Does these functions indicate the  population ‘birth-rate’ and ‘death-rate’ ?
![image](https://user-images.githubusercontent.com/431890/137581810-1ab93ffc-c477-4c63-9a31-14431912d69a.png)

![image](https://user-images.githubusercontent.com/431890/137581787-cf08be88-099a-47c8-99c8-532098d2aa06.png)
 
Thanks in advance for the support.

**Comment by bpatch** [comment]
Hi, thank you for your interest in BirDePy and kind words. Thank you for pointing out that this may be a bit confusing. In a future version I will likely add a message to the output which further clarifies how the output of birdepy.estimate() should be interpreted. 

---------------------------------------
1. The function birdepy.estimate() returns an object which has several attributes. Attribute 'p' corresponds to the estimated parameter values and is in the canonical order given by the table on this page (https://birdepy.github.io/processes.html). 

For example, running:

est = birdepy.estimate(obs_times, pop_sizes, p0, p_bounds, model='Ricker')
print(est.p)

will print out a list of length 4 which contains the estimated values of gamma, nu, alpha and c. Note that depending on how much data you have available, you may wish to use the key word arguments 'known_p' and 'idx_known_p' of birdepy.estimate() to specify some of the parameter values (e.g., setting c=1 when using the Ricker model) as described at https://birdepy.github.io/estimation.html#known-parameters . 

---------------------------------------
2. Yes, that is correct. Once the parameter values have been estimated, they can be used to determine the population birth-rate and death-rate for each population size z. Note that these quantities are functions of the population size z.
